### ISSUE TITLE
Decrypt key fail unexpected end of JSON input

### ISSUE THREAD

**Issue by justaskan** [fsn-dev/crossChain-Bridge#1]
I just installed crosschain-bridge.
In config file for KeystoreFile and PasswordFile I linked an empty address of 2 files but when I run oracleserver or swapserver I got this error :
```

panic: Decrypt key fail unexpected end of JSON input

goroutine 1 [running]:
github.com/fsn-dev/crossChain-Bridge/tokens/bridge.InitDcrm(0xc00007e3c0, 0x0)
	/home/hdev/testy/dcrm/crossChain-Bridge/tokens/bridge/bridge.go:121 +0x15db
github.com/fsn-dev/crossChain-Bridge/tokens/bridge.InitCrossChainBridge(0xc000025100)
	/home/hdev/testy/dcrm/crossChain-Bridge/tokens/bridge/bridge.go:60 +0x511
github.com/fsn-dev/crossChain-Bridge/worker.StartOracleWork()
	/home/hdev/testy/dcrm/crossChain-Bridge/worker/worker.go:37 +0xb4
main.swaporacle(0xc000034380, 0xc0004e6400, 0xe)
	/home/hdev/testy/dcrm/crossChain-Bridge/cmd/swaporacle/main.go:60 +0x1eb
github.com/urfave/cli/v2.(*App).RunContext(0xc0004d2480, 0xb90020, 0xc0000ba050, 0xc0000a01b0, 0x1, 0x1, 0x0, 0x0)
	/home/hdev/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:315 +0x6be
github.com/urfave/cli/v2.(*App).Run(...)
	/home/hdev/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
main.main()
	/home/hdev/testy/dcrm/crossChain-Bridge/cmd/swaporacle/main.go:45 +0x6d

```
what should I input in those files ?

**Comment by cross-chain** [comment]
please ref. to <https://github.com/fsn-dev/crossChain-Bridge#preparations>
